### PR TITLE
Add initial support for animal trading

### PR DESCRIPTION
**Pull request by thomotron**

### CODE REVIEW

**Review by SapphireMH — CHANGES_REQUESTED** [review]
This no longer works now that B18 has been released.

"MessageSound.Silent" is no longer supported and should be replaced with "MessageTypeDefOf.SilentInput"

**Comment by thomotron** [comment]
Cheers for the heads-up @thisismike97. I've recompiled my branch and tested it, so it should be good to go again.

**Comment by ghost** [comment]
@thomotron sound awesome! @Longwelwind should take a look at this!

**Comment by Ghoul159** [comment]
hey @thomotron could you provide a compiled download link of your version? :)
i want to trade my huskys.... ;)

and yes @Longwelwind should look at this...

**Comment by thexa4** [comment]
Seems to work, training and health isn't being transfered yet but having the ability to send them at all is nice :)

If you want to test this, I made a release with this and the health patch here: https://github.com/thexa4/Phi/releases/tag/v0.13-health-animals

**Pull request closed without merging**
